INSERT INTO job_applied
            (job_id,
            application_sent_date,
            custome_resume,
            resume_file_name,
            cover_letter_sent,
            cover_letter_file_name,
            status)
VALUES      (1, 
            '2023-10-01',
            'true',
            'resume_john_doe.pdf',
            'true',
            'cover_letter_john_doe.pdf',
            'submitted'),
            (2, 
            '2023-10-02',
            'false',
            'resume_jane_doe.pdf',
            'false',
            NULL,
            'interview scheduled'),
            (3, 
            '2023-10-03',
            'true',
            'resume_jack_smith.pdf',
            'true',
            'cover_letter_jack_smith.pdf',
            'offer received'),
            (4, 
            '2023-10-04',
            'false',
            'resume_emily_jones.pdf',
            'false',
            NULL,
            'rejected'),
            (5, 
            '2023-10-05',
            'true',
            'resume_michael_brown.pdf',
            'true',
            'cover_letter_michael_brown.pdf',
            'submitted');

SELECT * FROM job_applied;